@startchen E/R Diagram For Drop Alert
top to bottom direction

entity Store{
    storeID <<key>>
    storename
}

entity ProductType{ 
    typeID <<key>>
    typeName : String
}

relationship Inventory{
    storeID_externalID_composite <<key>>
    externalID
    typeID
    price
    quantity
    lastUpdated
}

Store -M- Inventory
Inventory -M- ProductType

@endchen