@startchen E/R Diagram For Workout Tracker
top to bottom direction

entity Store{
    storeID <<key>>
    storename
}

entity Product{
    productID <<key>>
    name
    typeID
}

entity ProductType{ 
    typeID <<key>>
    typeName : String
}

relationship Inventory{
    storeID
    productID
    externalID
    price
    quantity
    storeID_ProductID_composite <<key>>
}

relationship Has {
}

Store -M- Inventory
Inventory -M- Product
Product -M- Has
Has -1- ProductType


@endchen